### ISSUE TITLE
TypeError: Converting py args to operator properties: : keyword "view_align" unrecognized

### ISSUE THREAD

**Issue by killarny** [artellblender/auto_rig#16]
Using the latest Blender 2.8 as of May 16th (see git rev in the traceback below), and ARP 3.41.41.

When I select my mesh and hit the "Get Selected Objects" button, this traceback shows:

```
Traceback (most recent call last):
  File "C:\Users\killa\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\auto_rig_pro-master\auto_rig_smart.py", line 254, in execute
    _get_selected_objects()           
  File "C:\Users\killa\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\auto_rig_pro-master\auto_rig_smart.py", line 4544, in _get_selected_objects
    bpy.ops.object.empty_add(type='PLAIN_AXES', radius = 0.01, view_align=False, location=(0,0,0), rotation=(0, 0, 0))   
  File "C:\Program Files\Blender Foundation\blender-2.80.0-git.3076544c8c52-windows64\2.80\scripts\modules\bpy\ops.py", line 200, in __call__
    ret = op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties: : keyword "view_align" unrecognized

location: <unknown location>:-1
```

**Comment by LanGun** [comment]
Same issue using blender 2.8 as off May 19th.

**Comment by LanGun** [comment]
Look for a new version of ARP, 3.41.42

**Comment by artellblender** [comment]
Thanks for reporting, this is due to changes in the latest Blender 2.8 builds. This is fixed in the latest Auto-Rig Pro version.
