### ISSUE TITLE
[Export FBX] Error when exporting my animations to Unity (Generic & Universal tested)

### ISSUE THREAD

**Issue by MlleDR** [artellblender/auto_rig#21]
Using Blender 2.80 and AutoRig Pro version.
Error when exporting my animations to Unity (Generic & Universal tested) and the armature dissapears from the scene.

```
..............................Starting ARP FBX Export..............................

Create copies...
Created dummy mesh
Character objects: ['rig', 'rig_add', 'arp_dummy_mesh']
operating on object rig
operating on object rig_add
operating on object arp_dummy_mesh
Copied.

Setup Generic Rig...

Fix FBX rotation...
180 angle: c_root.x 180.00000500895632
180 angle: c_p_root.x 180.00000500895632
180 angle: c_waist_bend.x 180.00000500895632
180 angle: c_spine_01_bend.x 180.00000500895632
180 angle: c_spine_02_bend.x 180.00000500895632
180 angle: c_skull_01.x 180.00000500895632
180 angle: foot_ik_target.r 180.00000500895632
180 angle: c_foot_roll.r 180.00000500895632
180 angle: c_foot_roll_cursor.r 180.00000500895632
180 angle: foot_ik_target.l 180.00000500895632
180 angle: c_foot_roll.l 180.00000500895632
180 angle: c_foot_roll_cursor.l 180.00000500895632

Adding noise...
c_foot_roll.r Bone length to long, reset transforms and exit
    Done.
..............................Set Units x100..............................
Error: Cannot apply to a multi user: Object "rig_arpexport", Armature "rig", aborting
Error: Cannot apply to a multi user: Object "rig_add_arpexport", Armature "rig_add", aborting
Revert name changes...
Deleting baked actions...
Deleting copies...
removing armature rig_add
removing armature rig
Traceback (most recent call last):
  File "C:\Users\[USER]\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\auto_rig_pro-master\auto_rig_ge.py", line 582, in execute
    _set_units_x100_generic(self.armature_name, self.armature_add_name)
  File "C:\Users\[USER]\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\auto_rig_pro-master\auto_rig_ge.py", line 3011, in _set_units_x100_generic
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
  File "D:\ProgramFiles_D\blender-2.80rc2-windows64\2.80\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Cannot apply to a multi user: Object "rig_arpexport", Armature "rig", aborting
Error: Cannot apply to a multi user: Object "rig_add_arpexport", Armature "rig_add", aborting


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\[USER]\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\auto_rig_pro-master\auto_rig_ge.py", line 6109, in execute
    return ARP_OT_export_fbx.execute(self, context)
  File "C:\Users\[USER]\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\auto_rig_pro-master\auto_rig_ge.py", line 720, in execute
    set_active_object(self.current_selection[0])
  File "C:\Users\[USER]\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\auto_rig_pro-master\auto_rig_ge.py", line 1454, in set_active_object
    bpy.context.view_layer.objects.active = bpy.data.objects[object_name]
KeyError: 'bpy_prop_collection[key]: key "rig" not found'

location: <unknown location>:-1

location: <unknown location>:-1
```

**Comment by MlleDR** [comment]
Still present in Auto-Rig Pro 3.41.59 patch.

**Comment by artellblender** [comment]
Sorry for the late reply, i'm still trying to figure out how to enable email notifications when new issues are created.
Weird issue, is it possible to send the blend file for investigation? Removing or degrading the character mesh is recommended if you can't share it for privacy reasons.

**Comment by artellblender** [comment]
Considering the lack of information to reproduce the issue, I close it for now.
