### ISSUE TITLE
[AutoRig Pro: Smart] Errors and merged mesh on GetSelectedObjects

### ISSUE THREAD

**Issue by MlleDR** [artellblender/auto_rig#22]
I used the tool once and succeeded the whole process until the following issue #21 . For some reason, I wanted to go through the whole process again and start fresh but now, it's the very first steps that are causing issues.

1. First, when pressing on Get Seleceted Objects button after selecting my seperate meshes, I get the following errors. Note that those logs even show an attempt to remove and re-install the pro version:

```
addon_utils.disable: auto_rig_pro-master not loaded
Modules Installed (auto_rig_pro-master) from '[USER PATH...]\\auto_rig_pro-master.zip' into 'C:\\Users\\[USER]\\AppData\\Roaming\\Blender Foundation\\Blender\\2.80\\scripts\\addons'
addon_utils.disable: proxy_picker not loaded
Modules Installed (proxy_picker) from '[USER PATH...]\\proxy_picker.py' into 'C:\\Users\\[USER]\\AppData\\Roaming\\Blender Foundation\\Blender\\2.80\\scripts\\addons'
module changed on disk: 'C:\\Users\\[USER]\\AppData\\Roaming\\Blender Foundation\\Blender\\2.80\\scripts\\addons\\auto_rig_pro-master\\__init__.py' reloading...

 Starting Auto-Rig Pro Functions...

 Starting Auto-Rig Pro...

Blender version:  2.80 (sub 74)

 Starting Auto-Rig Pro: Smart...

 Starting Auto-Rig Pro: Remap...

 Starting Auto-Rig Pro: Game Engine Exporter...

module changed on disk: 'C:\\Users\\[USER]\\AppData\\Roaming\\Blender Foundation\\Blender\\2.80\\scripts\\addons\\proxy_picker.py' reloading...
Writing userprefs: 'C:\Users\[USER]\AppData\Roaming\Blender Foundation\Blender\2.80\config\userpref.blend' ok
Error: Cannot apply to a multi user: Object "body_temp", Mesh "Plane", aborting
Traceback (most recent call last):
  File "C:\Users\[USER]\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\auto_rig_pro-master\auto_rig_smart.py", line 254, in execute
    _get_selected_objects()
  File "C:\Users\[USER]\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\auto_rig_pro-master\auto_rig_smart.py", line 4521, in _get_selected_objects
    bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
  File "D:\ProgramFiles_D\blender-2.80rc2-windows64\2.80\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Cannot apply to a multi user: Object "body_temp", Mesh "Plane", aborting

location: <unknown location>:-1

location: <unknown location>:-1
```

2. Second, the seperate parts of my mesh are merged into a new mesh called **body_temp**.

![image](https://user-images.githubusercontent.com/27687330/62199630-22a7fb80-b384-11e9-9072-5e7869b7aa1f.png)

**Comment by artellblender** [comment]
1.Seems very similar to [the other issue](https://github.com/artellblender/auto_rig/issues/21).
2.This is normal, a temporary body mesh is created.

**Comment by artellblender** [comment]
Considering the lack of information to reproduce the issue, I close it for now.
