### ISSUE TITLE
Match to Rig giving error

### ISSUE THREAD

**Issue by jlamarche** [artellblender/auto_rig#25]
After doing the Smart -> Get Selected Objects, then lining up bones and hitting "Match to Rig", I get the following error in the final Blender 2.8 build:

    Traceback (most recent call last):
    File "/Users/jeff/Library/Application Support/Blender/2.80/scripts/addons/auto_rig_pro-master/auto_rig.py", line 1673, in execute
        _reset_stretches()      
    File "/Users/jeff/Library/Application Support/Blender/2.80/scripts/addons/auto_rig_pro-master/auto_rig.py", line 4321, in _reset_stretches
        auto_rig_reset.reset_all()
    File "/Users/jeff/Library/Application Support/Blender/2.80/scripts/addons/auto_rig_pro-master/auto_rig_reset.py", line 43, in reset_all
        set_inverse_child(bone.name, cns)
    TypeError: set_inverse_child() takes 1 positional argument but 2 were given

    location: <unknown location>:-1

[system-info.txt](https://github.com/artellblender/auto_rig/files/3562901/system-info.txt)

**Comment by jlamarche** [comment]
`set_inverse_child()` refers to a variable called cns, but doesn't have it in the definition. Changing it so it does:

    def set_inverse_child(b, cns):

Seems to fix this issue.

**Comment by artellblender** [comment]
Thanks for proposing the fix! The issue has been introduced with the previous Auto-Rig Pro update, it has been quickly fixed afterward (3.41.65).
