### ISSUE TITLE
Error when exporting FBX with linked armature

### ISSUE THREAD

**Issue by parmezan38** [artellblender/auto_rig#32]
I'm having issue with exporting the FBX file of my animation that was created with a linked armature.
Here's the error that I get after clicking export:
```
Python: Traceback (most recent call last):
  File "C:\Users\Parmezan38\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\auto_rig_pro-master\auto_rig_ge.py", line 6417, in execute
    return ARP_OT_export_fbx.execute(self, context)
  File "C:\Users\Parmezan38\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\auto_rig_pro-master\auto_rig_ge.py", line 646, in execute
    create_copies(self)     
  File "C:\Users\Parmezan38\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\auto_rig_pro-master\auto_rig_ge.py", line 1357, in create_copies
    bpy.context.active_object.data = bpy.context.active_object.data.copy()
AttributeError: 'NoneType' object has no attribute 'copy'

location: <unknown location>:-1
```
Everything else seems to work fine and this doesn't happen when trying to export the FBX from a normal Blender file that doesn't have the armature linked.
I have followed the guide for armature linking in the Auto-Rig Pro docs (http://www.lucky3d.fr/auto-rig-pro/doc/auto_rig.html#appending-linking-in-a-scene), and it seemed to work fine for a previous rig.

**Comment by artellblender** [comment]
This reports is 1 year old, closing
