### ISSUE TITLE
Export not working on Ubuntu Linux

### ISSUE THREAD

**Issue by zFunked** [artellblender/auto_rig#41]
When i want to export my model to Auto-Rig-Pro GLTF it crashes with the following messages:

`Python: Traceback (most recent call last):
  File "/home/funked/.config/blender/3.5/scripts/addons/auto_rig_pro-master/src/auto_rig_ge.py", line 8072, in execute
    return ARP_OT_export_fbx.execute(self, context)
  File "/home/funked/.config/blender/3.5/scripts/addons/auto_rig_pro-master/src/auto_rig_ge.py", line 1222, in execute
    from . import glTF2ExportUserExtension
ImportError: cannot import name 'glTF2ExportUserExtension' from 'auto_rig_pro-master.src' (unknown location)
`

When i export for FBX, it works fine on both OS', but i need GLB for Godot.

I already re-downloaded and re-installed the addons but that didn't help.

Suprisingly, it works fine on Windows (i have a dual-boot installation).

Both Blender installations run via Steam (Blender 3.5.0)

**Comment by zFunked** [comment]
Issue has been fixed in version 3.68.20
